flowers/config/routes.rb
Rails.application.routes.draw do
  resources :baby_clothes
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:'pages#index'
end

flowers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

flowers/app/models/baby_clothe.rb
class BabyClothe < ApplicationRecord
end

flowers/app/models/item.rb
class Item < ApplicationRecord
end

flowers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

flowers/app/controllers/baby_clothes_controller.rb
class BabyClothesController < ApplicationController
  before_action :set_baby_clothe, only: [:show, :edit, :update, :destroy]

  # GET /baby_clothes
  # GET /baby_clothes.json
  def index
    @baby_clothes = BabyClothe.all
  end

  # GET /baby_clothes/1
  # GET /baby_clothes/1.json
  def show
  end

  # GET /baby_clothes/new
  def new
    @baby_clothe = BabyClothe.new
  end

  # GET /baby_clothes/1/edit
  def edit
  end

  # POST /baby_clothes
  # POST /baby_clothes.json
  def create
    @baby_clothe = BabyClothe.new(baby_clothe_params)

    respond_to do |format|
      if @baby_clothe.save
        format.html { redirect_to @baby_clothe, notice: 'Baby clothe was successfully created.' }
        format.json { render :show, status: :created, location: @baby_clothe }
      else
        format.html { render :new }
        format.json { render json: @baby_clothe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /baby_clothes/1
  # PATCH/PUT /baby_clothes/1.json
  def update
    respond_to do |format|
      if @baby_clothe.update(baby_clothe_params)
        format.html { redirect_to @baby_clothe, notice: 'Baby clothe was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby_clothe }
      else
        format.html { render :edit }
        format.json { render json: @baby_clothe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /baby_clothes/1
  # DELETE /baby_clothes/1.json
  def destroy
    @baby_clothe.destroy
    respond_to do |format|
      format.html { redirect_to baby_clothes_url, notice: 'Baby clothe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baby_clothe
      @baby_clothe = BabyClothe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baby_clothe_params
      params.require(:baby_clothe).permit(:name, :size, :color)
    end
end

flowers/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :colour)
    end
end

flowers/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
end

flowers/app/helpers/application_helper.rb
module ApplicationHelper
end

flowers/app/helpers/baby_clothes_helper.rb
module BabyClothesHelper
end

flowers/app/helpers/items_helper.rb
module ItemsHelper
end

flowers/app/views/baby_clothes/_form.html.erb
<%= form_with(model: baby_clothe, local: true) do |form| %>
  <% if baby_clothe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(baby_clothe.errors.count, "error") %> prohibited this baby_clothe from being saved:</h2>

      <ul>
      <% baby_clothe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_area :color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

flowers/app/views/baby_clothes/edit.html.erb
<h1>Editing Baby Clothe</h1>

<%= render 'form', baby_clothe: @baby_clothe %>

<%= link_to 'Show', @baby_clothe %> |
<%= link_to 'Back', baby_clothes_path %>

flowers/app/views/baby_clothes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Baby Clothes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baby_clothes.each do |baby_clothe| %>
      <tr>
        <td><%= baby_clothe.name %></td>
        <td><%= baby_clothe.size %></td>
        <td><%= baby_clothe.color %></td>
        <td><%= link_to 'Show', baby_clothe %></td>
        <td><%= link_to 'Edit', edit_baby_clothe_path(baby_clothe) %></td>
        <td><%= link_to 'Destroy', baby_clothe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baby Clothe', new_baby_clothe_path %>

flowers/app/views/baby_clothes/new.html.erb
<h1>New Baby Baby...</h1>

<%= render 'form', baby_clothe: @baby_clothe %>

<%= link_to 'Back', baby_clothes_path %>

flowers/app/views/baby_clothes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @baby_clothe.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @baby_clothe.size %>
</p>

<p>
  <strong>Color:</strong>
  <%= @baby_clothe.color %>
</p>

<%= link_to 'Edit', edit_baby_clothe_path(@baby_clothe) %> |
<%= link_to 'Back', baby_clothes_path %>

flowers/app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_field :colour %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

flowers/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

flowers/app/views/items/index.html.erb
      <p id="notice"><%= notice %></p>
<%= link_to 'Home page', root_path %>
<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Colour</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.colour %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

flowers/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

flowers/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @item.colour %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

flowers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flowers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

flowers/app/views/pages/index.html.erb
<h1>Welcome to The Cake House</h1>

<%= link_to 'View all items', items_path %>